/* See COPYRIGHT for copyright information. */

#include <inc/x86.h>
#include <inc/mmu.h>
#include <inc/error.h>
#include <inc/string.h>
#include <inc/assert.h>

#include <kern/pmap.h>
#include <kern/kclock.h>

//
// Supporting mixed 4MB and 4KB pages
// ----------------------------------
//
// We'll keep track of 2 page free lists. One for 4k pages and one for 4m
// ones.
//
// Alloc:
// * if the size needed is >4k:
// ** we'll find a free slot in the 4m free list
// ** if empty, fail the request (fragmentation)
// * if size is <= 4k:
// ** we'll find a free slot in the 4k free list
// ** if empty, we'll find a free slot from 4m free list
// *** if emtpy, fail the request (out of mem)
// *** if not empty, remove four 4k pages from the 4m free list and
//     add three of those to the 4k free list. One of them is for alloc.
//
// Free
// * if page size is 4m, return the four 4k pages to 4m free list
// * if page size is <= 4k
// ** if page is 4m aligned
// *** if the next three pages are free (ref_link != null)
// **** add the page to 4m free list
// **** move the next three pages from 4k free list to 4m free list
// *** if any of the next three pages are not free
// **** return the page to 4k free list
// ** if page is not 4m aligned
// *** return the page to 4k free list
//

// These variables are set by i386_detect_memory()
size_t npages;			// Amount of physical memory (in pages)
static size_t npages_basemem;	// Amount of base memory (in pages)

// These variables are set in mem_init()
pde_t *kern_pgdir;		// Kernel's initial page directory
struct PageInfo *pages;		// Physical page state array
struct PageInfo *page_free_list;	// Free list of physical pages
struct PageInfo *spage_free_list;	// Free list of 4MB pages
static bool has_pse;

static bool mem_intersected(uint32_t startaddr1, uint32_t endaddr1,
	uint32_t startaddr2, uint32_t endaddr2);

bool mem_intersected(uint32_t startaddr1, uint32_t endaddr1,
	uint32_t startaddr2, uint32_t endaddr2)
{
	bool intersect = endaddr2 > startaddr1 && endaddr1 > startaddr2;
	return intersect;
}

// --------------------------------------------------------------
// Detect machine's physical memory setup.
// --------------------------------------------------------------

static int
nvram_read(int r)
{
	return mc146818_read(r) | (mc146818_read(r + 1) << 8);
}

static void
i386_detect_memory(void)
{
	size_t basemem, extmem, ext16mem, totalmem;

	// Use CMOS calls to measure available base & extended memory.
	// (CMOS calls return results in kilobytes.)
	basemem = nvram_read(NVRAM_BASELO);
	extmem = nvram_read(NVRAM_EXTLO);
	ext16mem = nvram_read(NVRAM_EXT16LO) * 64;

	// Calculate the number of physical pages available in both base
	// and extended memory.
	if (ext16mem)
		totalmem = 16 * 1024 + ext16mem;
	else if (extmem)
		totalmem = 1 * 1024 + extmem;
	else
		totalmem = basemem;

	npages = totalmem / (PGSIZE / 1024);
	npages_basemem = basemem / (PGSIZE / 1024);

	cprintf("Physical memory: %uK available, base = %uK, extended = %uK\n",
		totalmem, basemem, totalmem - basemem);
}


// --------------------------------------------------------------
// Set up memory mappings above UTOP.
// --------------------------------------------------------------

static void boot_map_region(pde_t *pgdir, uintptr_t va, size_t size, physaddr_t pa, int perm);
static void check_page_free_list(bool only_low_memory);
static void check_page_alloc(void);
static void check_kern_pgdir(void);
static physaddr_t check_va2pa(pde_t *pgdir, uintptr_t va, bool *spage);
static void check_page(void);
static void check_page_installed_pgdir(void);

// This simple physical memory allocator is used only while JOS is setting
// up its virtual memory system.  page_alloc() is the real allocator.
//
// If n>0, allocates enough pages of contiguous physical memory to hold 'n'
// bytes.  Doesn't initialize the memory.  Returns a kernel virtual address.
//
// If n==0, returns the address of the next free page without allocating
// anything.
//
// If we're out of memory, boot_alloc should panic.
// This function may ONLY be used during initialization,
// before the page_free_list list has been set up.
static void *
boot_alloc(uint32_t n)
{
	static char *nextfree;	// virtual address of next byte of free memory
	char *result;

	// Initialize nextfree if this is the first time.
	// 'end' is a magic symbol automatically generated by the linker,
	// which points to the end of the kernel's bss segment:
	// the first virtual address that the linker did *not* assign
	// to any kernel code or global variables.
	if (!nextfree) {
		extern char end[];
		nextfree = ROUNDUP((char *) end, PGSIZE);
	}

	// Allocate a chunk large enough to hold 'n' bytes, then update
	// nextfree.  Make sure nextfree is kept aligned
	// to a multiple of PGSIZE.
	//
	// LAB 2: Your code here.
	result = nextfree;

	if (n != 0) {
		// make sure we're not overflowing memory
		char * endaddr = nextfree + ROUNDUP(n, PGSIZE);
		if (PADDR(endaddr) / PGSIZE > npages)
			panic("Running out of memory.");
		nextfree = endaddr;
	}

	return result;
}

// Set up a two-level page table:
//    kern_pgdir is its linear (virtual) address of the root
//
// This function only sets up the kernel part of the address space
// (ie. addresses >= UTOP).  The user part of the address space
// will be setup later.
//
// From UTOP to ULIM, the user is allowed to read but not write.
// Above ULIM the user cannot read or write.
// static void do_showmappings(uintptr_t startva, uintptr_t endva);
void
mem_init(void)
{
	uint32_t cr0;
	size_t n;

	// Check for 4MB page size is supported
	uint32_t edx;
	cpuid(0x1, NULL, NULL, NULL, &edx);
	has_pse = edx & CPUID_PSE;
	if (has_pse)
	{
		cprintf("4MB pages supported\n");
		// turn on superpage
		uint32_t cr4 = rcr4();
		cr4 |= CR4_PSE;
		lcr4(cr4);
		cprintf("4MB pages turned on\n");
	}
	else
		cprintf("No 4MB page support\n");

	// Find out how much memory the machine has (npages & npages_basemem).
	i386_detect_memory();

	// Remove this line when you're ready to test this function.
	// panic("mem_init: This function is not finished\n");

	//////////////////////////////////////////////////////////////////////
	// create initial page directory.
	kern_pgdir = (pde_t *) boot_alloc(PGSIZE);
	memset(kern_pgdir, 0, PGSIZE);

	//////////////////////////////////////////////////////////////////////
	// Recursively insert PD in itself as a page table, to form
	// a virtual page table at virtual address UVPT.
	// (For now, you don't have understand the greater purpose of the
	// following line.)

	// Permissions: kernel R, user R
	kern_pgdir[PDX(UVPT)] = PADDR(kern_pgdir) | PTE_U | PTE_P;

	//////////////////////////////////////////////////////////////////////
	// Allocate an array of npages 'struct PageInfo's and store it in 'pages'.
	// The kernel uses this array to keep track of physical pages: for
	// each physical page, there is a corresponding struct PageInfo in this
	// array.  'npages' is the number of physical pages in memory.  Use memset
	// to initialize all fields of each struct PageInfo to 0.
	// Your code goes here:
	size_t pages_size = npages * sizeof(struct PageInfo);
	pages = (struct PageInfo *) boot_alloc(pages_size);
	memset(pages, 0, sizeof(struct PageInfo) * npages);

	//////////////////////////////////////////////////////////////////////
	// Now that we've allocated the initial kernel data structures, we set
	// up the list of free physical pages. Once we've done so, all further
	// memory management will go through the page_* functions. In
	// particular, we can now map memory using boot_map_region
	// or page_insert
	page_init();

	check_page_free_list(1);
	check_page_alloc();
	check_page();

	//////////////////////////////////////////////////////////////////////
	// Now we set up virtual memory

	//////////////////////////////////////////////////////////////////////
	// Map 'pages' read-only by the user at linear address UPAGES
	// Permissions:
	//    - the new image at UPAGES -- kernel R, user R
	//      (ie. perm = PTE_U | PTE_P)
	//    - pages itself -- kernel RW, user NONE
	// Your code goes here:

	// Note that the pages are alloc'ed by bootalloc and the pa region for pages are not
	// in free page list. So, this is safe.
	boot_map_region(kern_pgdir, UPAGES, ROUNDUP(pages_size, PGSIZE), PADDR(pages), PTE_U | PTE_P);

	//////////////////////////////////////////////////////////////////////
	// Use the physical memory that 'bootstack' refers to as the kernel
	// stack.  The kernel stack grows down from virtual address KSTACKTOP.
	// We consider the entire range from [KSTACKTOP-PTSIZE, KSTACKTOP)
	// to be the kernel stack, but break this into two pieces:
	//     * [KSTACKTOP-KSTKSIZE, KSTACKTOP) -- backed by physical memory
	//     * [KSTACKTOP-PTSIZE, KSTACKTOP-KSTKSIZE) -- not backed; so if
	//       the kernel overflows its stack, it will fault rather than
	//       overwrite memory.  Known as a "guard page".
	//     Permissions: kernel RW, user NONE
	// Your code goes here:

	// Note that when doing page_init(), we already marked 
	// cprintf("bootstack=0x%08x, bootstacktop=0x%08x\n", bootstack, bootstacktop);
	// struct PageInfo *ppbootstack = pa2page(PADDR(bootstack));
	// struct PageInfo *ppbootstacktop = pa2page(PADDR(bootstacktop));
	// cprintf("ppbootstack=0x%08x, ppbootstacktop=0x%08x\n", ppbootstack, ppbootstacktop);
	// assert(PTSIZE % (KSTKSIZE + KSTKGAP) == 0);
	// uintptr_t kstk_va = KSTACKTOP - PTSIZE;
	// no need to check wrap around as KSTACKTOP + KSTKGAP + KSTKSIZE will not wrap yet.
	// same for the for loop below

	// Note: bootstack and bootstacktop's physical addr are below the initial nextfree from bootalloc()
	// just simply map a single kernel stack [bootstack, bootstacktop) to pa[kstacktop - kstksize, kstacktop)
	assert(PADDR(bootstacktop) - PADDR(bootstack) == KSTKSIZE);
	boot_map_region(kern_pgdir, KSTACKTOP - KSTKSIZE, KSTKSIZE, PADDR(bootstack), PTE_W | PTE_P);
	boot_map_region(kern_pgdir, KSTACKTOP - PTSIZE, PTSIZE - KSTKSIZE, 0, 0);

	// while (kstk_va < KSTACKTOP) {
	// 	// make sure the kernel overflow stack is not allocated
	// 	uintptr_t kgap_end = kstk_va + KSTKGAP;
	// 	for (; kstk_va < kgap_end; kstk_va += PGSIZE) {
	// 		page_remove(kern_pgdir, (void *) kstk_va);
	// 	}
	// 	// map the page backed region
	// 	uintptr_t kstk_end = kstk_va + KSTKSIZE;
	// 	for (; kstk_va < kstk_end; kstk_va += PGSIZE) {
	// 		struct PageInfo *pp = page_alloc(0);
	// 		if (pp == NULL)
	// 			panic("Out of memory while allocating kernel stack at 0x%08x", kstk_va);
	// 		int piresult = page_insert(kern_pgdir, pp, (void *) kstk_va, PTE_W);
	// 		assert(piresult == 0);
	// 		// boot_map_region(kern_pgdir, kstk_va, PGSIZE, page2pa(pp), PTE_W);
	// 		if (kstk_va > 0xefff0000) {
	// 			a++;
	// 			assert(a > 0);
	// 		}
	// 	}
	// }


	//////////////////////////////////////////////////////////////////////
	// Map all of physical memory at KERNBASE.
	// Ie.  the VA range [KERNBASE, 2^32) should map to
	//      the PA range [0, 2^32 - KERNBASE)
	// We might not have 2^32 - KERNBASE bytes of physical memory, but
	// we just set up the mapping anyway.
	// Permissions: kernel RW, user NONE
	// Your code goes here:
	uint32_t perm = PTE_W | PTE_P;
	if (has_pse)
		perm |= PTE_PS;
	boot_map_region(kern_pgdir, KERNBASE, ~0 - KERNBASE, 0, perm);

	// Check that the initial page directory has been set up correctly.
	check_kern_pgdir();

	// Switch from the minimal entry page directory to the full kern_pgdir
	// page table we just created.	Our instruction pointer should be
	// somewhere between KERNBASE and KERNBASE+4MB right now, which is
	// mapped the same way by both page tables.
	//
	// If the machine reboots at this point, you've probably set up your
	// kern_pgdir wrong.
	// do_showmappings(0x0, 0xffffffff);
	lcr3(PADDR(kern_pgdir));

	check_page_free_list(0);

	// entry.S set the really important flags in cr0 (including enabling
	// paging).  Here we configure the rest of the flags that we care about.
	cr0 = rcr0();
	cr0 |= CR0_PE|CR0_PG|CR0_AM|CR0_WP|CR0_NE|CR0_MP;
	cr0 &= ~(CR0_TS|CR0_EM);
	lcr0(cr0);

	// Some more checks, only possible after kern_pgdir is installed.
	check_page_installed_pgdir();
}
// static void parse_perm(char * output, pte_t pte);
// void do_showmappings(uintptr_t startva, uintptr_t endva)
// {
// 	cprintf("Show mappings for VA [0x%08x, 0x%08x]\n", startva, endva);
// 	cprintf("\n%-10s | %-10s | %s\n", "VA", "PA", "PERMS (present|R/W|U/S|WriteThru|CacheEnabled|Accessed|Dirty|PS|Global)");
// 	for (int i = 0; i < NPDENTRIES; ++i) {
// 		pde_t *pd = kern_pgdir + i;
// 		if (*pd & PTE_P) {
// 			uintptr_t va = ((uintptr_t)i) << PDXSHIFT;
// 			physaddr_t pa = PTE_ADDR(*pd);
// 			char perm[20];
// 			parse_perm(perm, *pd);
// 			cprintf("0x%08x | 0x%08x | %s\n", va, pa, perm);
// 		}
// 	}
// }
// void
// parse_perm(char * output, pte_t pte)
// {
// 	strcpy(output, "-|R|S|-|T|-|-|4k|-");
// 	if (pte & PTE_P)
// 		output[0] = 'P';
// 	if (pte & PTE_W)
// 		output[2] = 'W';
// 	if (pte & PTE_U)
// 		output[4] = 'U';
// 	if (pte & PTE_PWT)
// 		output[6] = 'T';
// 	if (pte & PTE_PCD)
// 		output[8] = '-';
// 	if (pte & PTE_A)
// 		output[10] = 'A';
// 	if (pte & PTE_D)
// 		output[12] = 'D';
// 	if (pte & PTE_PS)
// 		output[15] = 'M';
// 	if (pte & PTE_G)
// 		output[17] = 'G';
// }

// --------------------------------------------------------------
// Tracking of physical pages.
// The 'pages' array has one 'struct PageInfo' entry per physical page.
// Pages are reference counted, and free pages are kept on a linked list.
// --------------------------------------------------------------

//
// Initialize page structure and memory free list.
// After this is done, NEVER use boot_alloc again.  ONLY use the page
// allocator functions below to allocate and deallocate physical
// memory via the page_free_list.
//
void
page_init(void)
{
	// The example code here marks all physical pages as free.
	// However this is not truly the case.  What memory is free?
	//  1) Mark physical page 0 as in use.
	//     This way we preserve the real-mode IDT and BIOS structures
	//     in case we ever need them.  (Currently we don't, but...)
	//  2) The rest of base memory, [PGSIZE, npages_basemem * PGSIZE)
	//     is free.
	//  3) Then comes the IO hole [IOPHYSMEM, EXTPHYSMEM), which must
	//     never be allocated.
	//  4) Then extended memory [EXTPHYSMEM, ...).
	//     Some of it is in use, some is free. Where is the kernel
	//     in physical memory?  Which pages are already in use for
	//     page tables and other data structures?
	//
	// Change the code to reflect this.
	// NB: DO NOT actually touch the physical memory corresponding to
	// free pages!

	for (physaddr_t i = 0; i < npages; ) {
		physaddr_t pa, pa_nextfree;
		pa = page2pa(&pages[i]);
		assert(pa == i * PGSIZE);
		pa_nextfree = PADDR(boot_alloc(0));
		bool spage_aligned = ((pa & (SPGSIZE - 1)) == 0);
		// if this is a superpage
		bool is_spage = has_pse && spage_aligned && ((i + PG_PER_SPG) < npages);
		if (pa == 0 ||
			mem_intersected(IOPHYSMEM, EXTPHYSMEM, pa, pa + SPGSIZE) ||
			mem_intersected(EXTPHYSMEM,	pa_nextfree, pa, pa + SPGSIZE) ||
			mem_intersected(PADDR(bootstack) + KSTKSIZE,
					PADDR((void *) KSTACKTOP), pa, pa + SPGSIZE))
			is_spage = false;
	
		// cprintf("pa_nextfree=0x%08x\n", pa_nextfree);

		//
		// hole: pp_ref = 0
		// kernel alloc: pp_ref = 1
		//

		if (pa == 0) {// || pa == KERNBASE) {
			// preserver 1st page for real-mode IDT and BIOS
			//pages[0].pp_ref = 1;
			// also need to leave a hole in the corresponding kernel mem to avoid
			// allocating and deallocating the pages to the corresponding physical memory hole.
		}
		else if (pa >= IOPHYSMEM && pa < EXTPHYSMEM) {
			// IO hole must never be allocated
			// kernel pages are never released. So, setting ref is optional.
			// pages[i].pp_ref = 1;
		}
		else if (pa >= EXTPHYSMEM && pa < pa_nextfree) {
			// kernel actually starts at EXTPHYSMEM == PADDR((void*)0xF0100000)
			assert(PADDR((void*)0xF0100000) == EXTPHYSMEM);
			// start of kernel until the nextfree is allocated already
			// kernel pages are never released. So, setting ref is optional
			// but we'll set it to denote that it's kernel used space, not a
			// hole.
			pages[i].pp_ref = 1;
		}
		// else if (mem mapped io zone) {
		// 	// may need to leave a hole for Memory-mapped I/O??
		//	// but we can't support that much mem, so this is out of range
		// }
		else if (pa >= PADDR(bootstack) + KSTKSIZE &&
				pa < PADDR(bootstacktop)) {
			// reserve mem for kernel stack
			// this is already below nextfree so we should not need to do this
			assert((uintptr_t) bootstacktop == KSTACKTOP);
			pages[i].pp_ref = 1;
		}
		else if (is_spage) {
			for (int j = 0; j < PG_PER_SPG; ++j) {
				assert(i+j < npages);
				pages[i+j].pp_ref = 0;
				pages[i+j].pp_link = spage_free_list;
				spage_free_list = &pages[i+j];
			}
		}
		else {
			pages[i].pp_ref = 0;
			pages[i].pp_link = page_free_list;
			page_free_list = &pages[i];
		}
		i += is_spage ? PG_PER_SPG : 1;
	}
}

//
// Allocates a physical page.  If (alloc_flags & ALLOC_ZERO), fills the entire
// returned physical page with '\0' bytes.  Does NOT increment the reference
// count of the page - the caller must do these if necessary (either explicitly
// or via page_insert).
//
// Be sure to set the pp_link field of the allocated page to NULL so
// page_free can check for double-free bugs.
//
// Returns NULL if out of free memory.
//
// Hint: use page2kva and memset
int oo = 0;
struct PageInfo *
page_alloc(int alloc_flags)
{
	struct PageInfo *pp;
	// Fill this function in
	if (page_free_list == NULL)
		return NULL;

	pp = page_free_list;
	page_free_list = pp->pp_link;
	pp->pp_link = NULL;

	if (alloc_flags & ALLOC_ZERO)
		memset(page2kva(pp), 0, PGSIZE);

	if ((uintptr_t)pp == 0xf0119868) {
		oo++;
	}

	return pp;
}

//
// Return a page to the free list.
// (This function should only be called when pp->pp_ref reaches 0.)
//
void
page_free(struct PageInfo *pp)
{
	// Fill this function in
	// Hint: You may want to panic if pp->pp_ref is nonzero or
	// pp->pp_link is not NULL.
	if (pp->pp_ref != 0)
		panic("page_free() when pp_ref is %d", pp->pp_ref);
	if (pp->pp_link != NULL)
		panic("page_free() when pp_link is 0x%08x", pp->pp_ref);
	pp->pp_link = page_free_list;
	page_free_list = pp;
}

//
// Decrement the reference count on a page,
// freeing it if there are no more refs.
//
void
page_decref(struct PageInfo* pp)
{
	if (--pp->pp_ref == 0)
		page_free(pp);
}

// Given 'pgdir', a pointer to a page directory, pgdir_walk returns
// a pointer to the page table entry (PTE) for linear address 'va'.
// This requires walking the two-level page table structure.
//
// The relevant page table page might not exist yet.
// If this is true, and create == false, then pgdir_walk returns NULL.
// Otherwise, pgdir_walk allocates a new page table page with page_alloc.
//    - If the allocation fails, pgdir_walk returns NULL.
//    - Otherwise, the new page's reference count is incremented,
//	the page is cleared,
//	and pgdir_walk returns a pointer into the new page table page.
//
// Hint 1: you can turn a PageInfo * into the physical address of the
// page it refers to with page2pa() from kern/pmap.h.
//
// Hint 2: the x86 MMU checks permission bits in both the page directory
// and the page table, so it's safe to leave permissions in the page
// directory more permissive than strictly necessary.
//
// Hint 3: look at inc/mmu.h for useful macros that mainipulate page
// table and page directory entries.
//
pte_t *
pgdir_walk(pde_t *pgdir, const void *va, int create)
{
	pde_t *ppde = pgdir + PDX(va);
	if (*ppde == 0) {
		// return null if dir entry not exist and create is false
		if (create == PGDIR_WALK_NO_CREATE)
			return NULL;
	}
	if (*ppde == 0) {
		// create page table entry if not exist
		if (create == PGDIR_WALK_CREATE_REG) {
			// alloc the page for the page table
			struct PageInfo *pg_info = page_alloc(ALLOC_ZERO);
			if (pg_info == 0)
				return NULL;
			++pg_info->pp_ref;
			physaddr_t pgpa = page2pa(pg_info);
			// set up the pgdir to point to the new page
			*ppde = pgpa | PTE_P | PTE_W | PTE_U;
		}
		else if (create == PGDIR_WALK_CREATE_SUPER) {
			return ppde;
		}
		else
			panic("Unknown pgdir_walk create enum %d\n", create);
	}
	// obtain the page entry
	if ((*ppde & PTE_PS) != 0) {
		// superpage, pde is the pte
		return ppde;
	}
	// 4k page, pte is from pagetable
	pte_t *pgtable = (pte_t *)KADDR(PTE_ADDR(*ppde));
	pte_t *ppte = pgtable + PTX(va);

	return ppte;
}

//
// Map [va, va+size) of virtual address space to physical [pa, pa+size)
// in the page table rooted at pgdir.  Size is a multiple of PGSIZE, and
// va and pa are both page-aligned.
// Use permission bits perm|PTE_P for the entries.
//
// This function is only intended to set up the ``static'' mappings
// above UTOP. As such, it should *not* change the pp_ref field on the
// mapped pages.
//
// Hint: the TA solution uses pgdir_walk
static void
boot_map_region(pde_t *pgdir, uintptr_t va, size_t size, physaddr_t pa, int perm)
{
	// Fill this function in
	uintptr_t va_start = va;
	uintptr_t va_end = va + size;
	// the va >= va_start is because the range could wrap around for unsigned arithmetic
	bool spage = ((perm & PTE_PS) != 0);
	uintptr_t pgsize = spage ? SPGSIZE : PGSIZE;
	int create = spage ? PGDIR_WALK_CREATE_SUPER : PGDIR_WALK_CREATE_REG;
	while (va < va_end && va >= va_start) {
		pte_t *ppte = pgdir_walk(pgdir, (const void*) va, create);
		assert(ppte != NULL);
		if (*ppte == 0) {
			// add mapping
			*ppte = pa | perm;
		}
		assert(PTE_ADDR(*ppte) == pa);
		va += pgsize;
		pa += pgsize;
	}
}

//
// Map the physical page 'pp' at virtual address 'va'.
// The permissions (the low 12 bits) of the page table entry
// should be set to 'perm|PTE_P'.
//
// Requirements
//   - If there is already a page mapped at 'va', it should be page_remove()d.
//   - If necessary, on demand, a page table should be allocated and inserted
//     into 'pgdir'.
//   - pp->pp_ref should be incremented if the insertion succeeds.
//   - The TLB must be invalidated if a page was formerly present at 'va'.
//
// Corner-case hint: Make sure to consider what happens when the same
// pp is re-inserted at the same virtual address in the same pgdir.
// However, try not to distinguish this case in your code, as this
// frequently leads to subtle bugs; there's an elegant way to handle
// everything in one code path.
//
// RETURNS:
//   0 on success
//   -E_NO_MEM, if page table couldn't be allocated
//
// Hint: The TA solution is implemented using pgdir_walk, page_remove,
// and page2pa.
//
int
page_insert(pde_t *pgdir, struct PageInfo *pp, void *va, int perm)
{
	// Fill this function in
	assert(pp != NULL);
	assert(pp->pp_link == NULL);
	bool spage = ((perm & PTE_PS) != 0);
	int create = spage ? PGDIR_WALK_CREATE_SUPER : PGDIR_WALK_CREATE_REG;
	pte_t *ppte = pgdir_walk(pgdir, va, create);
	if (ppte == NULL)
		return -E_NO_MEM;
	physaddr_t pa = page2pa(pp);
	if (*ppte != 0) {
		physaddr_t pte_pa = PTE_ADDR(*ppte);
		// edge case - mapping pp to the same va
		if (pte_pa == pa) {
			// 1st way
			assert(pp->pp_ref > 0);
			*ppte = pa | perm | PTE_P;
			return 0;
		}
		// normal case - remove the page
		page_remove(pgdir, va);
		// // edge case - mapping pp to the same va
		// if (pte_pa == pa) {
		// 	// 2nd way
		// 	struct PageInfo *pg_info = page_alloc(0);
		// 	assert(pp == pg_info);
		// }
	}
	++pp->pp_ref;
	*ppte = pa | perm | PTE_P;

	return 0;
}

//
// Return the page mapped at virtual address 'va'.
// If pte_store is not zero, then we store in it the address
// of the pte for this page.  This is used by page_remove and
// can be used to verify page permissions for syscall arguments,
// but should not be used by most callers.
//
// Return NULL if there is no page mapped at va.
//
// Hint: the TA solution uses pgdir_walk and pa2page.
//
struct PageInfo *
page_lookup(pde_t *pgdir, void *va, pte_t **pte_store)
{
	// Fill this function in
	pte_t *ppte = pgdir_walk(pgdir, va, PGDIR_WALK_NO_CREATE);
	if (ppte == NULL)
		return NULL;
	if ((*ppte | PTE_P) == 0)
		return NULL;
	if (pte_store != 0)
		*pte_store = ppte;
	// get the page info
	struct PageInfo *pg_info = pa2page(PTE_ADDR(*ppte));
	return pg_info;
}

//
// Unmaps the physical page at virtual address 'va'.
// If there is no physical page at that address, silently does nothing.
//
// Details:
//   - The ref count on the physical page should decrement.
//   - The physical page should be freed if the refcount reaches 0.
//   - The pg table entry corresponding to 'va' should be set to 0.
//     (if such a PTE exists)
//   - The TLB must be invalidated if you remove an entry from
//     the page table.
//
// Hint: The TA solution is implemented using page_lookup,
// 	tlb_invalidate, and page_decref.
//
void
page_remove(pde_t *pgdir, void *va)
{
	// Fill this function in
	pte_t *ppte = 0;
	struct PageInfo *pg_info = page_lookup(pgdir, va, &ppte);
	if (pg_info != NULL) {
		page_decref(pg_info);
		*ppte = 0;
		tlb_invalidate(pgdir, va);
	}
}

//
// Invalidate a TLB entry, but only if the page tables being
// edited are the ones currently in use by the processor.
//
void
tlb_invalidate(pde_t *pgdir, void *va)
{
	// Flush the entry only if we're modifying the current address space.
	// For now, there is only one address space, so always invalidate.
	invlpg(va);
}


// --------------------------------------------------------------
// Checking functions.
// --------------------------------------------------------------

//
// Check that the pages on the page_free_list are reasonable.
//
static void
check_page_free_list(bool only_low_memory)
{
	struct PageInfo *pp, *spp;
	unsigned pdx_limit = only_low_memory ? 1 : NPDENTRIES;
	int nfree_basemem = 0, nfree_extmem = 0;
	char *first_free_page;

	if (!page_free_list)
		panic("'page_free_list' is a null pointer!");

	if (only_low_memory) {
		// Move pages with lower addresses first in the free
		// list, since entry_pgdir does not map all pages.
		struct PageInfo *pp1, *pp2;
		struct PageInfo **tp[2] = { &pp1, &pp2 };
		for (pp = page_free_list; pp; pp = pp->pp_link) {
			int pagetype = PDX(page2pa(pp)) >= pdx_limit;
			*tp[pagetype] = pp;
			tp[pagetype] = &pp->pp_link;
		}
		*tp[1] = 0;
		*tp[0] = pp2;
		page_free_list = pp1;
	}

	// if there's a page that shouldn't be on the free list,
	// try to make sure it eventually causes trouble.
	for (pp = page_free_list; pp; pp = pp->pp_link) {
		if (PDX(page2pa(pp)) < pdx_limit)
			memset(page2kva(pp), 0x97, 128);
	}

	for (spp = spage_free_list; spp; spp = spp->pp_link) {
		if (PDX(page2pa(spp)) < pdx_limit)
			memset(page2kva(spp), 0x98, 128);
	}

	first_free_page = (char *) boot_alloc(0);
	for (pp = page_free_list; pp; pp = pp->pp_link) {
		// check that we didn't corrupt the free list itself
		assert(pp >= pages);
		assert(pp < pages + npages);
		assert(((char *) pp - (char *) pages) % sizeof(*pp) == 0);

		// check a few pages that shouldn't be on the free list
		assert(page2pa(pp) != 0);
		assert(page2pa(pp) != IOPHYSMEM);
		assert(page2pa(pp) != EXTPHYSMEM - PGSIZE);
		assert(page2pa(pp) != EXTPHYSMEM);
		assert(page2pa(pp) < EXTPHYSMEM || (char *) page2kva(pp) >= first_free_page);

		if (page2pa(pp) < EXTPHYSMEM)
			++nfree_basemem;
		else
			++nfree_extmem;
	}

	assert(nfree_basemem > 0);
	assert(nfree_extmem > 0);

	// my added assert
	assert(nfree_basemem == IOPHYSMEM / PGSIZE - 1);
	// assert(nfree_extmem == npages * PGSIZE - PADDR(first_free_page));

	nfree_basemem = 0;
	nfree_extmem = 0;
	for (spp = spage_free_list; spp; spp = spp->pp_link) {
		// check that we didn't corrupt the free list itself
		assert(spp >= pages);
		assert(spp < pages + npages);
		assert(((char *) spp - (char *) pages) % sizeof(*spp) == 0);

		// check a few pages that shouldn't be on the free list
		assert(page2pa(spp) != 0);
		assert(page2pa(spp) != IOPHYSMEM);
		assert(page2pa(spp) != EXTPHYSMEM - PGSIZE);
		assert(page2pa(spp) != EXTPHYSMEM);
		assert(page2pa(spp) < EXTPHYSMEM || (char *) page2kva(spp) >= first_free_page);

		if (page2pa(spp) < EXTPHYSMEM)
			++nfree_basemem;
		else
			++nfree_extmem;
	}

	// 640k low mem is not enough to hold even 1 superpage which is 4mb
	assert(nfree_basemem == 0);
	assert(nfree_extmem > 0);

	cprintf("check_page_free_list() succeeded!\n");
}

//
// Check the physical page allocator (page_alloc(), page_free(),
// and page_init()).
//
static void
check_page_alloc(void)
{
	struct PageInfo *pp, *pp0, *pp1, *pp2;
	int nfree;
	struct PageInfo *fl;
	char *c;
	int i;

	if (!pages)
		panic("'pages' is a null pointer!");

	// check number of free pages
	for (pp = page_free_list, nfree = 0; pp; pp = pp->pp_link)
		++nfree;

	// should be able to allocate three pages
	pp0 = pp1 = pp2 = 0;
	assert((pp0 = page_alloc(0)));
	assert((pp1 = page_alloc(0)));
	assert((pp2 = page_alloc(0)));

	assert(pp0);
	assert(pp1 && pp1 != pp0);
	assert(pp2 && pp2 != pp1 && pp2 != pp0);
	assert(page2pa(pp0) < npages*PGSIZE);
	assert(page2pa(pp1) < npages*PGSIZE);
	assert(page2pa(pp2) < npages*PGSIZE);

	// temporarily steal the rest of the free pages
	fl = page_free_list;
	page_free_list = 0;

	// should be no free memory
	assert(!page_alloc(0));

	// free and re-allocate?
	page_free(pp0);
	page_free(pp1);
	page_free(pp2);
	pp0 = pp1 = pp2 = 0;
	assert((pp0 = page_alloc(0)));
	assert((pp1 = page_alloc(0)));
	assert((pp2 = page_alloc(0)));
	assert(pp0);
	assert(pp1 && pp1 != pp0);
	assert(pp2 && pp2 != pp1 && pp2 != pp0);
	assert(!page_alloc(0));

	// test flags
	memset(page2kva(pp0), 1, PGSIZE);
	page_free(pp0);
	assert((pp = page_alloc(ALLOC_ZERO)));
	assert(pp && pp0 == pp);
	c = page2kva(pp);
	for (i = 0; i < PGSIZE; i++)
		assert(c[i] == 0);

	// give free list back
	page_free_list = fl;

	// free the pages we took
	page_free(pp0);
	page_free(pp1);
	page_free(pp2);

	// number of free pages should be the same
	for (pp = page_free_list; pp; pp = pp->pp_link)
		--nfree;
	assert(nfree == 0);

	cprintf("check_page_alloc() succeeded!\n");
}

//
// Checks that the kernel part of virtual address space
// has been setup roughly correctly (by mem_init()).
//
// This function doesn't test every corner case,
// but it is a pretty good sanity check.
//

static void
check_kern_pgdir(void)
{
	uint32_t i, n;
	pde_t *pgdir;

	pgdir = kern_pgdir;

	// check pages array
	n = ROUNDUP(npages*sizeof(struct PageInfo), PGSIZE);
	for (i = 0; i < n; i += PGSIZE)
		assert(check_va2pa(pgdir, UPAGES + i, NULL) == PADDR(pages) + i);


	// check phys mem
	for (i = 0; i < npages * PGSIZE; ) {
		bool spage = false;
		assert(check_va2pa(pgdir, KERNBASE + i, &spage) == i);
		i += spage ? SPGSIZE : PGSIZE;
	}

	// check kernel stack
	for (i = 0; i < KSTKSIZE; i += PGSIZE) {
		physaddr_t mypa1 = check_va2pa(pgdir, KSTACKTOP - KSTKSIZE + i, NULL);
		physaddr_t mypa2 = PADDR(bootstack) + i;
		assert(mypa1 == mypa2);
	}
	assert(check_va2pa(pgdir, KSTACKTOP - PTSIZE, NULL) == ~0);

	// check PDE permissions
	for (i = 0; i < NPDENTRIES; i++) {
		switch (i) {
		case PDX(UVPT):
		case PDX(KSTACKTOP-1):
		case PDX(UPAGES):
			assert(pgdir[i] & PTE_P);
			break;
		default:
			if (i >= PDX(KERNBASE)) {
				assert(pgdir[i] & PTE_P);
				assert(pgdir[i] & PTE_W);
			} else
				assert(pgdir[i] == 0);
			break;
		}
	}
	cprintf("check_kern_pgdir() succeeded!\n");
}

// This function returns the physical address of the page containing 'va',
// defined by the page directory 'pgdir'.  The hardware normally performs
// this functionality for us!  We define our own version to help check
// the check_kern_pgdir() function; it shouldn't be used elsewhere.
// Note: returns spage from last param.

static physaddr_t
check_va2pa(pde_t *pgdir, uintptr_t va, bool *spage)
{
	pte_t *p;

	pgdir = &pgdir[PDX(va)];
	if (!(*pgdir & PTE_P))
		return ~0;
	if (*pgdir & PTE_PS) {
		if (spage)
			*spage = true;
		return PTE_ADDR(*pgdir);
	}
	p = (pte_t*) KADDR(PTE_ADDR(*pgdir));
	if (!(p[PTX(va)] & PTE_P))
		return ~0;
	return PTE_ADDR(p[PTX(va)]);
}


// check page_insert, page_remove, &c
static void
check_page(void)
{
	struct PageInfo *pp, *pp0, *pp1, *pp2;
	struct PageInfo *fl;
	pte_t *ptep, *ptep1;
	void *va;
	int i;
	extern pde_t entry_pgdir[];

	// should be able to allocate three pages
	pp0 = pp1 = pp2 = 0;
	assert((pp0 = page_alloc(0)));
	assert((pp1 = page_alloc(0)));
	assert((pp2 = page_alloc(0)));

	assert(pp0);
	assert(pp1 && pp1 != pp0);
	assert(pp2 && pp2 != pp1 && pp2 != pp0);

	// temporarily steal the rest of the free pages
	fl = page_free_list;
	page_free_list = 0;

	// should be no free memory
	assert(!page_alloc(0));

	// there is no page allocated at address 0
	assert(page_lookup(kern_pgdir, (void *) 0x0, &ptep) == NULL);

	// there is no free memory, so we can't allocate a page table
	assert(page_insert(kern_pgdir, pp1, 0x0, PTE_W) < 0);

	// free pp0 and try again: pp0 should be used for page table
	page_free(pp0);
	assert(page_insert(kern_pgdir, pp1, 0x0, PTE_W) == 0);
	assert(PTE_ADDR(kern_pgdir[0]) == page2pa(pp0));
	assert(check_va2pa(kern_pgdir, 0x0, NULL) == page2pa(pp1));
	assert(pp1->pp_ref == 1);
	assert(pp0->pp_ref == 1);

	// should be able to map pp2 at PGSIZE because pp0 is already allocated for page table
	assert(page_insert(kern_pgdir, pp2, (void*) PGSIZE, PTE_W) == 0);
	assert(check_va2pa(kern_pgdir, PGSIZE, NULL) == page2pa(pp2));
	assert(pp2->pp_ref == 1);

	// should be no free memory
	assert(!page_alloc(0));

	// should be able to map pp2 at PGSIZE because it's already there
	assert(page_insert(kern_pgdir, pp2, (void*) PGSIZE, PTE_W) == 0);
	assert(check_va2pa(kern_pgdir, PGSIZE, NULL) == page2pa(pp2));
	assert(pp2->pp_ref == 1);

	// pp2 should NOT be on the free list
	// could happen in ref counts are handled sloppily in page_insert
	assert(!page_alloc(0));

	// check that pgdir_walk returns a pointer to the pte
	ptep = (pte_t *) KADDR(PTE_ADDR(kern_pgdir[PDX(PGSIZE)]));
	assert(pgdir_walk(kern_pgdir, (void*)PGSIZE, PGDIR_WALK_NO_CREATE) == ptep+PTX(PGSIZE));

	// should be able to change permissions too.
	assert(page_insert(kern_pgdir, pp2, (void*) PGSIZE, PTE_W|PTE_U) == 0);
	assert(check_va2pa(kern_pgdir, PGSIZE, NULL) == page2pa(pp2));
	assert(pp2->pp_ref == 1);
	assert(*pgdir_walk(kern_pgdir, (void*) PGSIZE, PGDIR_WALK_NO_CREATE) & PTE_U);
	assert(kern_pgdir[0] & PTE_U);

	// should be able to remap with fewer permissions
	assert(page_insert(kern_pgdir, pp2, (void*) PGSIZE, PTE_W) == 0);
	assert(*pgdir_walk(kern_pgdir, (void*) PGSIZE, PGDIR_WALK_NO_CREATE) & PTE_W);
	assert(!(*pgdir_walk(kern_pgdir, (void*) PGSIZE, PGDIR_WALK_NO_CREATE) & PTE_U));

	// should not be able to map at PTSIZE because need free page for page table
	assert(page_insert(kern_pgdir, pp0, (void*) PTSIZE, PTE_W) < 0);

	// insert pp1 at PGSIZE (replacing pp2)
	assert(page_insert(kern_pgdir, pp1, (void*) PGSIZE, PTE_W) == 0);
	assert(!(*pgdir_walk(kern_pgdir, (void*) PGSIZE, PGDIR_WALK_NO_CREATE) & PTE_U));

	// should have pp1 at both 0 and PGSIZE, pp2 nowhere, ...
	assert(check_va2pa(kern_pgdir, 0, NULL) == page2pa(pp1));
	assert(check_va2pa(kern_pgdir, PGSIZE, NULL) == page2pa(pp1));
	// ... and ref counts should reflect this
	assert(pp1->pp_ref == 2);
	assert(pp2->pp_ref == 0);

	// pp2 should be returned by page_alloc
	assert((pp = page_alloc(0)) && pp == pp2);

	// unmapping pp1 at 0 should keep pp1 at PGSIZE
	page_remove(kern_pgdir, 0x0);
	assert(check_va2pa(kern_pgdir, 0x0, NULL) == ~0);
	assert(check_va2pa(kern_pgdir, PGSIZE, NULL) == page2pa(pp1));
	assert(pp1->pp_ref == 1);
	assert(pp2->pp_ref == 0);

	// test re-inserting pp1 at PGSIZE
	assert(page_insert(kern_pgdir, pp1, (void*) PGSIZE, 0) == 0);
	assert(pp1->pp_ref == 1);
	assert(pp1->pp_link == NULL);

	// unmapping pp1 at PGSIZE should free it
	page_remove(kern_pgdir, (void*) PGSIZE);
	assert(check_va2pa(kern_pgdir, 0x0, NULL) == ~0);
	assert(check_va2pa(kern_pgdir, PGSIZE, NULL) == ~0);
	assert(pp1->pp_ref == 0);
	assert(pp2->pp_ref == 0);

	// so it should be returned by page_alloc
	assert((pp = page_alloc(0)) && pp == pp1);

	// should be no free memory
	assert(!page_alloc(0));

	// forcibly take pp0 back
	assert(PTE_ADDR(kern_pgdir[0]) == page2pa(pp0));
	kern_pgdir[0] = 0;
	assert(pp0->pp_ref == 1);
	pp0->pp_ref = 0;

	// check pointer arithmetic in pgdir_walk
	page_free(pp0);
	va = (void*)(PGSIZE * NPDENTRIES + PGSIZE);
	ptep = pgdir_walk(kern_pgdir, va, PGDIR_WALK_CREATE_REG);
	ptep1 = (pte_t *) KADDR(PTE_ADDR(kern_pgdir[PDX(va)]));
	assert(ptep == ptep1 + PTX(va));
	kern_pgdir[PDX(va)] = 0;
	pp0->pp_ref = 0;

	// check that new page tables get cleared
	memset(page2kva(pp0), 0xFF, PGSIZE);
	page_free(pp0);
	pgdir_walk(kern_pgdir, 0x0, PGDIR_WALK_CREATE_REG);
	ptep = (pte_t *) page2kva(pp0);
	for(i=0; i<NPTENTRIES; i++)
		assert((ptep[i] & PTE_P) == 0);
	kern_pgdir[0] = 0;
	pp0->pp_ref = 0;

	// give free list back
	page_free_list = fl;

	// free the pages we took
	page_free(pp0);
	page_free(pp1);
	page_free(pp2);

	cprintf("check_page() succeeded!\n");
}

// check page_insert, page_remove, &c, with an installed kern_pgdir
static void
check_page_installed_pgdir(void)
{
	struct PageInfo *pp, *pp0, *pp1, *pp2;
	struct PageInfo *fl;
	pte_t *ptep, *ptep1;
	uintptr_t va;
	int i;

	// check that we can read and write installed pages
	pp1 = pp2 = 0;
	assert((pp0 = page_alloc(0)));
	assert((pp1 = page_alloc(0)));
	assert((pp2 = page_alloc(0)));
	page_free(pp0);
	memset(page2kva(pp1), 1, PGSIZE);
	memset(page2kva(pp2), 2, PGSIZE);
	page_insert(kern_pgdir, pp1, (void*) PGSIZE, PTE_W);
	assert(pp1->pp_ref == 1);
	assert(*(uint32_t *)PGSIZE == 0x01010101U);
	page_insert(kern_pgdir, pp2, (void*) PGSIZE, PTE_W);
	assert(*(uint32_t *)PGSIZE == 0x02020202U);
	assert(pp2->pp_ref == 1);
	assert(pp1->pp_ref == 0);
	*(uint32_t *)PGSIZE = 0x03030303U;
	assert(*(uint32_t *)page2kva(pp2) == 0x03030303U);
	page_remove(kern_pgdir, (void*) PGSIZE);
	assert(pp2->pp_ref == 0);

	// forcibly take pp0 back
	assert(PTE_ADDR(kern_pgdir[0]) == page2pa(pp0));
	kern_pgdir[0] = 0;
	assert(pp0->pp_ref == 1);
	pp0->pp_ref = 0;

	// free the pages we took
	page_free(pp0);

	cprintf("check_page_installed_pgdir() succeeded!\n");
}
